-- E-Commerce Business Analysis (Advanced SQL Project)

-- 1. Total revenue generated by the business
SELECT SUM(total_amount) AS total_revenue
FROM orders;

-- 2. Total number of orders placed
SELECT COUNT(order_id) AS total_orders
FROM orders;

-- 3. Average order value
SELECT 
    AVG(total_amount) AS average_order_value
FROM orders;

-- 4. Monthly revenue trend
SELECT 
    DATE_FORMAT(order_date, '%Y-%m') AS month,
    SUM(total_amount) AS monthly_revenue
FROM orders
GROUP BY DATE_FORMAT(order_date, '%Y-%m')
ORDER BY month;

-- 5. Month-over-month growth rate
WITH monthly_sales AS (
    SELECT 
        DATE_FORMAT(order_date, '%Y-%m') AS month,
        SUM(total_amount) AS revenue
    FROM orders
    GROUP BY DATE_FORMAT(order_date, '%Y-%m')
)
SELECT 
    month,
    revenue,
    LAG(revenue) OVER (ORDER BY month) AS previous_month,
    ROUND(
        (revenue - LAG(revenue) OVER (ORDER BY month)) /
        LAG(revenue) OVER (ORDER BY month) * 100, 2
    ) AS growth_rate
FROM monthly_sales;

-- 6. Top 10 customers by total spend
SELECT 
    customer_id,
    SUM(total_amount) AS total_spent
FROM orders
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 10;

-- 7. Customer lifetime value (CLV)
SELECT 
    customer_id,
    SUM(total_amount) AS lifetime_value
FROM orders
GROUP BY customer_id;

-- 8. Repeat vs one-time customers
SELECT 
    customer_id,
    COUNT(order_id) AS total_orders,
    CASE 
        WHEN COUNT(order_id) = 1 THEN 'One-time Customer'
        ELSE 'Repeat Customer'
    END AS customer_type
FROM orders
GROUP BY customer_id;

-- 9. Customer segmentation based on spending
SELECT 
    customer_id,
    SUM(total_amount) AS total_spent,
    CASE 
        WHEN SUM(total_amount) >= 5000 THEN 'High Value'
        WHEN SUM(total_amount) BETWEEN 2000 AND 4999 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS segment
FROM orders
GROUP BY customer_id;

-- 10. Top performing products
SELECT 
    p.product_name,
    SUM(oi.quantity * oi.unit_price) AS revenue
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY revenue DESC;

-- 11. Product quantity sold (demand analysis)
SELECT 
    p.product_name,
    SUM(oi.quantity) AS total_units_sold
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_units_sold DESC;

-- 12. Best performing product categories
SELECT 
    p.category,
    SUM(oi.quantity * oi.unit_price) AS category_revenue
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY category_revenue DESC;

-- 13. Revenue contribution by category (% share)
WITH category_revenue AS (
    SELECT 
        p.category,
        SUM(oi.quantity * oi.unit_price) AS revenue
    FROM order_items oi
    JOIN products p ON oi.product_id = p.product_id
    GROUP BY p.category
)
SELECT 
    category,
    revenue,
    ROUND(revenue / (SELECT SUM(revenue) FROM category_revenue) * 100, 2) AS revenue_share
FROM category_revenue
ORDER BY revenue DESC;

-- 14. Regional sales performance
SELECT 
    region,
    SUM(total_amount) AS revenue
FROM orders
GROUP BY region
ORDER BY revenue DESC;

-- 15. Best performing region per revenue contribution
SELECT 
    region,
    SUM(total_amount) AS revenue,
    RANK() OVER (ORDER BY SUM(total_amount) DESC) AS region_rank
FROM orders
GROUP BY region;

-- 16. Inactive customers (no purchase in last 90 days)
SELECT 
    customer_id,
    MAX(order_date) AS last_purchase_date
FROM orders
GROUP BY customer_id
HAVING MAX(order_date) < DATE_SUB(CURDATE(), INTERVAL 90 DAY);

-- 17. New vs returning customers (monthly acquisition)
SELECT 
    DATE_FORMAT(order_date, '%Y-%m') AS month,
    COUNT(DISTINCT customer_id) AS active_customers
FROM orders
GROUP BY DATE_FORMAT(order_date, '%Y-%m')
ORDER BY month;

-- 18. Top 3 products per category
WITH ranked_products AS (
    SELECT 
        p.category,
        p.product_name,
        SUM(oi.quantity * oi.unit_price) AS revenue,
        RANK() OVER (
            PARTITION BY p.category 
            ORDER BY SUM(oi.quantity * oi.unit_price) DESC
        ) AS rnk
    FROM order_items oi
    JOIN products p ON oi.product_id = p.product_id
    GROUP BY p.category, p.product_name
)
SELECT *
FROM ranked_products
WHERE rnk <= 3;

-- 19. High-value customers contribution to total revenue
WITH customer_revenue AS (
    SELECT 
        customer_id,
        SUM(total_amount) AS revenue
    FROM orders
    GROUP BY customer_id
)
SELECT 
    customer_id,
    revenue,
    ROUND(revenue / (SELECT SUM(revenue) FROM customer_revenue) * 100, 2) AS contribution_percentage
FROM customer_revenue
ORDER BY revenue DESC;

-- 20. Business health summary (quick snapshot)
SELECT 
    (SELECT SUM(total_amount) FROM orders) AS total_revenue,
    (SELECT COUNT(order_id) FROM orders) AS total_orders,
    (SELECT AVG(total_amount) FROM orders) AS avg_order_value;
